version: '3.9'

services:
  frontend:
    image: yogahub-frontend
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

  backend:
    image: yogahub-backend
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - flaskapp

  flaskapp:
    image: yogahub-python
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
